site_name: Unit 1 - Software Design and Development

theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    #- navigation.footer
    - navigation.tabs
plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html    
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

copyright: Copyright &copy; 2025 Pixel&Wood Computer Science Tuition

extra_css:
  - Styles/extra.css



nav:
  - Home: https://www.bbc.co.uk/news
  - Development Methodologies:
      - Explanation: '1.0-Development-Methodologies/1.1-Introduction.md'
      - The Software Development Lifecycle: '1.0-Development-Methodologies/1.2-The-Software-Development-Lifecycle.md'
      - The Waterfall Method: '1.0-Development-Methodologies/1.3-The-Waterfall-Method.md'
      - The Six Stages of Development: '1.0-Development-Methodologies/1.4-The-Six-Stages-of-Development.md'
  - Analysis:
      - Explanation: '2.0-Analysis/2.1-Explanation.md'
  - Design:
      - Explanation: '3.0-Design/3.1-Explanation.md'
  - Implementation:
      - Variables & Assignment:
        - What you need to Know: '4.0-Implementation/4.1-Variables-&-Assignment/4.1.1-What-you-need-to-Know.md'
        - Explanation: '4.0-Implementation/4.1-Variables-&-Assignment/4.1.2-Explanation.md'
        - Exam Theory: '4.0-Implementation/4.1-Variables-&-Assignment/4.1.3-Exam-Theory.md'
        - Worked Example: '4.0-Implementation/4.1-Variables-&-Assignment/4.1.4-Worked-Example.md'
        - Test Quiz: '4.0-Implementation/4.1-Variables-&-Assignment/test quiz.md'
      - Simple Selection:
        - What you need to Know: '4.0-Implementation/4.2-Simple-Selection/4.2.1-What-you-need-to-Know.md'
        - Explanation: '4.0-Implementation/4.2-Simple-Selection/4.2.2-Explanation.md'
        - Exam Theory: '4.0-Implementation/4.2-Simple-Selection/4.2.3-Exam-Theory.md'
        - Worked Example: '4.0-Implementation/4.2-Simple-Selection/4.2.4-Worked-Example.md'
      - Complex Selection:
        - Explanation: '4.0-Implementation/4.3-Complex-Selection/4.3.1-Explanation.md'
        - Exam Theory: '4.0-Implementation/4.3-Complex-Selection/4.3.2-Exam-Theory.md'
        - Analysis: '4.0-Implementation/4.3-Complex-Selection/4.3.3-Analysis.md'
        - Program Design: '4.0-Implementation/4.3-Complex-Selection/4.3.4-Program-Design.md'
        - Implementation: '4.0-Implementation/4.3-Complex-Selection/4.3.5-Implementation.md'
      - Fixed Loops:
        - Explanation: '4.0-Implementation/4.4-Fixed-Loops/4.4.1-Explanation.md'
        - Exam Theory: '4.0-Implementation/4.4-Fixed-Loops/4.4.2-Exam-Theory.md'
        - Analysis: '4.0-Implementation/4.4-Fixed-Loops/4.4.3-Analysis.md'
        - Program Design: '4.0-Implementation/4.4-Fixed-Loops/4.4.4-Program-Design.md'
        - Implementation: '4.0-Implementation/4.4-Fixed-Loops/4.4.5-Implementation.md'
      - Conditional Loops:
        - Explanation: '4.0-Implementation/4.5-Conditional-Loops/4.5.1-Explanation.md'
        - Exam Theory: '4.0-Implementation/4.5-Conditional-Loops/4.5.2-Exam-Theory.md'
        - Analysis: '4.0-Implementation/4.5-Conditional-Loops/4.5.3-Analysis.md'
        - Program Design: '4.0-Implementation/4.5-Conditional-Loops/4.5.4-Program-Design.md'
        - Implementation: '4.0-Implementation/4.5-Conditional-Loops/4.5.5-Implementation.md'
      - Predefined Functions:
        - Explanation: '4.0-Implementation/4.2-Selection/4.2.1-Explanation.md'
        - Exam Theory: '4.0-Implementation/4.2-Selection/4.2.2-Exam-Theory.md'
        - Analysis: '4.0-Implementation/4.2-Selection/4.2.3-Analysis.md'
        - Program Design: '4.0-Implementation/4.2-Selection/4.2.4-Program-Design.md'
        - Implementation: '4.0-Implementation/4.2-Selection/4.2.5-Implementation.md'
      - Standard Algorithms:
        - Explanation: '4.0-Implementation/4.2-Selection/4.2.1-Explanation.md'
        - Exam Theory: '4.0-Implementation/4.2-Selection/4.2.2-Exam-Theory.md'
        - Analysis: '4.0-Implementation/4.2-Selection/4.2.3-Analysis.md'
        - Program Design: '4.0-Implementation/4.2-Selection/4.2.4-Program-Design.md'
        - Implementation: '4.0-Implementation/4.2-Selection/4.2.5-Implementation.md'
  - Testing:
        - Explantion: '3.0-Testing/3.1-Explanation.md'
        - Types of Test Data: '3.0-Testing/3.2-Types-of-Test-Data.md'
        - Testing Tables: '3.0-Testing/3.3-Testing-Tables.md'
        - Errors: '3.0-Testing/3.4-Errors.md'
  - Evaluation:
        - Explanation: '4.0-Evaluation/4.1-Explanation.md'
        - Fitness for Purpose: '4.0-Evaluation/4.2-Fitness-for-Purpose.md'
        - Efficient use of Coding Constructs: '4.0-Evaluation/4.3-Efficient-use-of-Coding-Constructs.md'
        - Robustness: '4.0-Evaluation/4.4-Robustness.md'
        - Readability: '4.0-Evaluation/4.5-Readability.md'
        - Evaluation Summary: '4.0-Evaluation/4.6-Evaluation-Summary.md'

      